WEB2021Apr_P04_T4/Models/Competition.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using WEB2021Apr_P04_T4.Models.Validation;

namespace WEB2021Apr_P04_T4.Models
{
    public class Competition
    {
        [Display(Name = "Competition ID")]
        [ValidateCompetitionModification]
        public int CompetitionID { get; set; }

        [Display(Name = "Interest ID")]
        [ValidateInterestDefault]
        public int AreaInterestID { get; set; }

        [Display(Name = "Competition Name")]
        [Required]
        [StringLength(255)]
        [ValidateCompetitionExists]
        public string CompetitionName { get; set; }

        [Display(Name = "Start Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [ValidateCompetitionStart]
        public DateTime? StartDate { get; set; }

        [Display(Name = "End Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [ValidateCompetitionEnd]
        public DateTime? EndDate { get; set; }

        [Display(Name = "Result Released Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [ValidateCompetitionResult]
        public DateTime? ResultReleasedDate { get; set; }
    }
}

WEB2021Apr_P04_T4/Models/CompetitionViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using WEB2021Apr_P04_T4.Models.Validation;

namespace WEB2021Apr_P04_T4.Models
{
    public class CompetitionViewModel
    {
        [Display(Name = "Competition ID")]
        [ValidateCompetitionModification]
        public int CompetitionID { get; set; }

        [Display(Name = "Area Interest")]
        public string Name { get; set; }

        [Display(Name = "Competition Name")]
        [Required]
        [StringLength(255)]
        [ValidateCompetitionExists]
        public string CompetitionName { get; set; }

        [Display(Name = "Start Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime? StartDate { get; set; }

        [Display(Name = "End Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime? EndDate { get; set; }

        [Display(Name = "Result Released Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime? ResultReleasedDate { get; set; }


    }
}

WEB2021Apr_P04_T4/Controllers/CompetitionController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WEB2021Apr_P04_T4.DAL;
using WEB2021Apr_P04_T4.Models;

namespace WEB2021Apr_P04_T4.Controllers
{
    public class CompetitionController : Controller
    {
        private CompetitionDAL competitionContext = new CompetitionDAL();
        private AreaInterestDAL areaInterestContext = new AreaInterestDAL();

        // GET: CompetitionController
        public ActionResult Index()
        {
            //If not admin, cannot access
            if ((HttpContext.Session.GetString("Role") == null) || (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            //Get all competition from DB
            List<Competition> competitionList = competitionContext.GetAllCompetition();
            return View(competitionList);
        }

        // GET: CompetitionController/Details/5
        public ActionResult Details(int id)
        {
            //If not admin, cannot access
            if ((HttpContext.Session.GetString("Role") == null) || (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null)
            { //Query string parameter not provided
              //Return to listing page, not allowed to edit
                return RedirectToAction("Index");
            }
            //Get details of competition
            Competition competition = competitionContext.GetDetails(id);
            //If query id not in db, redirect out
            if (competition.CompetitionName == null)
            {
                //Return to listing page, not allowed to edit
                return RedirectToAction("Index");
            }
            CompetitionViewModel competitionVM = MapToCompetitionVM(competition);
            return View(competitionVM);
        }

        public CompetitionViewModel MapToCompetitionVM(Competition competition)
        {
            string interestName = "";
            
            List<AreaInterest> interestList = areaInterestContext.GetAllAreaInterest();
            foreach (AreaInterest interest in interestList)
            {
                if (interest.AreaInterestID == competition.AreaInterestID)
                {
                    interestName = interest.Name;
                    //Exit the foreach loop once the name is found
                    break;
                }
            }
            
            CompetitionViewModel competitionVM = new CompetitionViewModel
            {
                CompetitionID = competition.CompetitionID,
                Name = interestName,
                CompetitionName = competition.CompetitionName,
                StartDate = competition.StartDate,
                EndDate = competition.EndDate,
                ResultReleasedDate = competition.ResultReleasedDate
            };
            return competitionVM;
        }

        private List<AreaInterest> GetAllAreaInterests()
        {
            // Get a list of interest from database
            List<AreaInterest> areaInterestList = areaInterestContext.GetAllAreaInterest();
            Console.WriteLine(areaInterestList);
            // Adding a select prompt at the first row of the list
            areaInterestList.Insert(0, new AreaInterest
            {
                AreaInterestID = 0,
                Name = "--Select--"
            });
            Console.WriteLine(areaInterestList);
            return areaInterestList;
        }

        // GET: CompetitionController/Create
        public ActionResult Create()
        {
            //If not admin, cannot access
            if ((HttpContext.Session.GetString("Role") == null) || (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            //Populate dropdown list
            ViewData["InterestList"] = GetAllAreaInterests();
            return View();
        }

        // POST: CompetitionController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Competition competition)
        {
            //Populate list for drop-down list
            //in case of the need to return to Edit.cshtml view
            ViewData["InterestList"] = GetAllAreaInterests();
            if (ModelState.IsValid)
            {
                //Update record to database
                competition.CompetitionID= competitionContext.Add(competition);
                return RedirectToAction("Index");
            }
            else
            {
                //Input validation fails, return to the view
                //to display error message
                return View(competition);
            }
        }

        
        // GET: CompetitionController/Edit/5
        public ActionResult Edit(int id)
        {
            //If not admin, cannot access
            if ((HttpContext.Session.GetString("Role") == null) || (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null)
            { //Query string parameter not provided
              //Return to listing page, not allowed to edit
                return RedirectToAction("Index");
            }
            ViewData["InterestList"] = GetAllAreaInterests();
            Competition competition = competitionContext.GetDetails(id);
            //Check against functional requirement criteria and redirect to error if needed
            if (competitionContext.IsModifiable(id))
            {
                TempData["ErrorMsg"] = "Sorry! A competitor has joined and cannot be modified";
                if (competition.EndDate < DateTime.Today)
                {
                   
                    TempData["ErrorMsg"] = "Sorry! The competition has ended and cannot be modified";
                    return RedirectToAction("DisplayError", "Home" );
                }
               
                return RedirectToAction("DisplayError", "Home");
            }
            if (competition.CompetitionName == null)
            {
                //Invalid query string parameter 
                //Return to listing page, not allowed to edit
                return RedirectToAction("Index");
            }
            return View(competition);
        }

        // POST: CompetitionController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Competition competition)
        {
            ViewData["InterestList"] = GetAllAreaInterests();

            if (ModelState.IsValid)
            {
                //Update record to database
                competitionContext.Update(competition);
                return RedirectToAction("Index");
            }
            else
            {
                //Input validation fails, return to the view
                //to display error message
                return View(competition);
            }
        }

        // GET: CompetitionController/Delete/5
        public ActionResult Delete(int id)
        {
            // Stop accessing the action if not logged in or account not in the "Admin" role
            if ((HttpContext.Session.GetString("Role") == null) || (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null)
            {
                //Query string parameter not provided
                //Return to listing page, not allowed to edit
                return RedirectToAction("Index");
            }
            Competition competition= competitionContext.GetDetails(id);
            //Check against functional requirement criteria and redirect to error if needed
            if (competitionContext.IsModifiable(id))
            {
                TempData["ErrorMsg"] = "Sorry! A competitor has joined and cannot be modified";
                if (competition.EndDate < DateTime.Today)
                {

                    TempData["ErrorMsg"] = "Sorry! The competition has ended and cannot be modified";
                    return RedirectToAction("DisplayError", "Home");
                }

                return RedirectToAction("DisplayError", "Home");
            }
            if (competition.CompetitionName == null)
            {
                //Invalid query string parameter 
                //Return to listing page, not allowed to edit
                return RedirectToAction("Index");
            }
            return View(competition);
        }

        // POST: CompetitionController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Competition competition)
        {
            ModelState.Remove("AreaInterestID");
            if (ModelState.IsValid)
            {
                // Delete the record from database
                competitionContext.Delete(competition.CompetitionID);
                //Redirect user 
                return RedirectToAction("Index");
            }
            else
            {
                //Input validation fails, return to the Delete view
                //to display error message
                return View(competition);
            }
        }
    }
}

WEB2021Apr_P04_T4/Views/Competition/Create.cshtml
@model WEB2021Apr_P04_T4.Models.Competition

@{
    ViewData["Title"] = "Create";
}

<h4 class="PageTitle">Create Competition</h4>
<hr />


<form asp-action="Create">
    <fieldset class="FormContent">
        <div class="form-group row">
            <label asp-for="CompetitionName"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="CompetitionName" class="form-control" />
                <span asp-validation-for="CompetitionName"
                      class="text-danger"></span>
            </div>
        </div>


        <div class="form-group row">
            <label asp-for="AreaInterestID"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <!-- Drop-down list displaying Branch Address,
            with Branch Number as returned value -->
                <select asp-for="AreaInterestID"
                        asp-items="@(new SelectList(
 @ViewData["InterestList"] as List <AreaInterest>,
 "AreaInterestID", "Name"))"
                        class="form-control"></select>
                <span asp-validation-for="AreaInterestID"
                      class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="StartDate"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate"
                      class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="EndDate"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate"
                      class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="ResultReleasedDate"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="ResultReleasedDate" class="form-control" />
                <span asp-validation-for="ResultReleasedDate"
                      class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <input type="submit" value="Create"
                       class="btn btn-primary" />
            </div>
        </div>
        <div>
            <a asp-action="Index">Back to List</a>
        </div>
    </fieldset>
</form>

WEB2021Apr_P04_T4/Views/Competition/Delete.cshtml
@model WEB2021Apr_P04_T4.Models.Competition

@{
    ViewData["Title"] = "Delete";
}

<h4 class="PageTitle">Delete Competition Record</h4>
<hr />
<form asp-action="Delete">
    <fieldset class="FormContent">
        <legend>Are you sure to delete this record?</legend>
        <div class="form-group row">
            <label asp-for="CompetitionID"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="CompetitionID" readonly
                       class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="CompetitionName"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="CompetitionName" readonly
                       class="form-control-plaintext" />
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <span asp-validation-for="CompetitionID"
                      class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <input type="submit" value="Delete"
                       class="btn btn-primary" />
            </div>
        </div>
        <div>
            <a asp-action="Index">Back to List</a>
        </div>
    </fieldset>
</form>

WEB2021Apr_P04_T4/Views/Competition/Details.cshtml
@model WEB2021Apr_P04_T4.Models.CompetitionViewModel

@{
    ViewData["Title"] = "Details";
}
<h4 class="PageTitle">View Competition Details</h4>
<hr />
<fieldset class="FormContent">
    <div class="form-group row">
        <label asp-for="CompetitionID"
               class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9 form-control-plaintext">
            @Html.Display("CompetitionID")
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Name" class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9 form-control-plaintext">
            @Html.Display("Name")
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="CompetitionName"
               class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9 form-control-plaintext">
            @Html.Display("CompetitionName")
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="StartDate"
               class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9 form-control-plaintext">
            @Html.Display("StartDate")
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="EndDate"
               class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9 form-control-plaintext">
            @Html.Display("EndDate")
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="ResultReleasedDate"
               class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9 form-control-plaintext">
            @Html.Display("ResultReleasedDate")
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-9 offset-sm-3">
            <a asp-action="Edit" asp-controller="Competition"
               asp-route-id="@Model.CompetitionID">Edit</a> |
            <a asp-action="Delete" asp-controller="Competition"
               asp-route-id="@Model.CompetitionID">Delete</a> |
            <a asp-action="Index"
               asp-controller="Competition">Return</a>
        </div>
    </div>
</fieldset>

WEB2021Apr_P04_T4/Views/Competition/Edit.cshtml
@model WEB2021Apr_P04_T4.Models.Competition

@{
    ViewData["Title"] = "Edit";
}

<h4 class="PageTitle">Edit Competition</h4>
<hr />


<form asp-action="Edit">
    <fieldset class="FormContent">
        <div class="form-group row">
            <label asp-for="CompetitionID"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="CompetitionID" readonly
                       class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="CompetitionName"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="CompetitionName" class="form-control" />
                <span asp-validation-for="CompetitionName"
                      class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-3 col-form-label">Interest</label>
            <div class="col-sm-9 col-md-5">
                <!-- Drop-down list displaying Branch Address,
            with Branch Number as returned value -->
                <select asp-for="AreaInterestID"
                        asp-items="@(new SelectList(
 @ViewData["InterestList"] as List <AreaInterest>,
 "AreaInterestID", "Name"))"
                        class="form-control"></select>
                <span asp-validation-for="AreaInterestID"
                      class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="StartDate"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate"
                      class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="EndDate"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate"
                      class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="ResultReleasedDate"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="ResultReleasedDate" class="form-control" />
                <span asp-validation-for="ResultReleasedDate"
                      class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <span asp-validation-for="CompetitionID"
                      class="text-danger"></span>
            </div>
        </div>


        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <input type="submit" value="Create"
                       class="btn btn-primary" />
            </div>
        </div>
        <div>
            <a asp-action="Index">Back to List</a>
        </div>
    </fieldset>
</form>

WEB2021Apr_P04_T4/Views/Competition/Index.cshtml
@model IEnumerable<WEB2021Apr_P04_T4.Models.Competition>

@{
    ViewData["Title"] = "Index";
}

<h4 class="PageTitle">View Competition</h4>
<p><a asp-action="Create">Create New Competition</a></p>
<!-- Add a partial view to display a list of staff records
 in a tabular format. -->
<partial name="~/Views/Competition/_ViewCompetition.cshtml" model="@Model" />

WEB2021Apr_P04_T4/Views/Competition/_ViewCompetition.cshtml
@model IEnumerable<WEB2021Apr_P04_T4.Models.Competition>

@if (Model.ToList().Count > 0)
{
    <div class="table-responsive">
        <table id="viewStaff" class="table table-striped table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>Competition ID</th>
                    <th>Competition Name</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td>@item.CompetitionID.ToString()</td>
                    <td>@item.CompetitionName</td>
                    <td>
                        <a asp-action="Edit" asp-controller="Competition"
                           asp-route-id="@item.CompetitionID">Edit</a> |
                        <a asp-action="Details" asp-controller="Competition"
                           asp-route-id="@item.CompetitionID">Details</a> |
                        <a asp-action="Delete" asp-controller="Competition"
                           asp-route-id="@item.CompetitionID">Delete</a> |
                        <a asp-action="Details" asp-controller="CompetitionJudge"
                           asp-route-id="@item.CompetitionID">Judges</a>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <span style="color:red">No record found!</span>
}