WEB2021Apr_P04_T4/Models/CompetitionScore.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using WEB2021Apr_P04_T4.Models.Validation;

namespace WEB2021Apr_P04_T4.Models
{
    public class CompetitionScore
    {
        [Required(ErrorMessage = "Please select a criteria to grade.")]
        [Display(Name = "Criteria ID")]
        public int CriteriaID { get; set; }

        [Required(ErrorMessage = "Please enter a CompetitorID to grade.")]
        [Display(Name = "Competitor ID")]
        public int CompetitorID { get; set; }

        [Required(ErrorMessage = "Please select a Competition to grade.")]
        [Display(Name = "Competition ID")]
        public int CompetitionID { get; set; }

        [Display(Name = "Score")]
        [Range(0, 10, ErrorMessage = "Please enter a score from 0 to 10.")]
        public int Score { get; set; }

    }
}

WEB2021Apr_P04_T4/Controllers/CompetitionScoreController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WEB2021Apr_P04_T4.DAL;
using WEB2021Apr_P04_T4.Models;

namespace WEB2021Apr_P04_T4.Controllers
{
    public class CompetitionScoreController : Controller
    {
        private CompetitionScoreDAL scoreContext = new CompetitionScoreDAL();
        private CompetitionDAL competitionContext = new CompetitionDAL();
        private CriteriaDAL criteriaContext = new CriteriaDAL();
        private CompetitionSubmissionDAL submissionContext = new CompetitionSubmissionDAL();

        // GET: CompetitionScore
        public ActionResult Index()
        {
            // Stop accessing the action if not logged in
            // or account not in the "Judge" role
            string loginID = HttpContext.Session.GetString("LoginID");
            if ((HttpContext.Session.GetString("Role") == null) ||
            (HttpContext.Session.GetString("Role") != "Judge"))
            {
                return RedirectToAction("Index", "Home");
            }
            List<CompetitionScore> scoreList = scoreContext.GetAllScore(Convert.ToInt32(loginID));
            return View(scoreList);
        }

        private List<Competition> GetAvailableCompetition(int JudgeID)
        {
            // Get a list of competitions from database
            List<Competition> competitionList = criteriaContext.GetAvailableCompetition(JudgeID);
            Console.WriteLine(competitionList);
            // Adding a select prompt at the first row of the competition list
            competitionList.Insert(0, new Competition
            {
                CompetitionID = 0,
                CompetitionName = "--Select--"
            });
            Console.WriteLine(competitionList);
            return competitionList;
        }

        private List<Criteria> GetAvailableCriteria(int JudgeID)
        {
            // Get a list of criterias based on selected competitionID from database
            List<Criteria> criteriaList = criteriaContext.GetAvailableCriteria(JudgeID);
            Console.WriteLine(criteriaList);
            // Adding a select prompt at the first row of the criteria list
            criteriaList.Insert(0, new Criteria
            {
                CriteriaID = 0,
                CriteriaName = "--Select--"
            });
            Console.WriteLine(criteriaList);
            return criteriaList;
        }

        //private List<CompetitionSubmission> GetAvailableSubmissions(int CompetitorID)
        //{
        //    // Get a list of branches from database
        //    List<CompetitionSubmission> submissionList = submissionContext.GetAvailableSubmissions(CompetitorID);
        //    Console.WriteLine(submissionList);
        //    // Adding a select prompt at the first row of the branch list
        //    submissionList.Insert(0, new CompetitionSubmission
        //    {
        //        CompetitorID = 0
        //    });
        //    Console.WriteLine(submissionList);
        //    return submissionList;
        //}


        // GET: CompetitionScore/Create
        public ActionResult Create()
        {
            // Stop accessing the action if not logged in
            // or account not in the "Judge" role
            if ((HttpContext.Session.GetString("Role") == null) ||
            (HttpContext.Session.GetString("Role") != "Judge"))
            {
                return RedirectToAction("Index", "Home");
            }
            string loginID = HttpContext.Session.GetString("LoginID");
            ViewData["scoreList"] = GetAllScore(Convert.ToInt32(loginID));
            ViewData["competitionList"] = GetAvailableCompetition(Convert.ToInt32(loginID));
            ViewData["CriteriaList"] = GetAvailableCriteria(Convert.ToInt32(loginID));
            //ViewData["submissionList"] = GetAvailableSubmissions(Convert.ToInt32(loginID));
            return View();
        }

        private List<CompetitionScore> GetAllScore(int JudgeID)
        {
            // Get a list of scores from database
            List<CompetitionScore> scoreList = scoreContext.GetAllScore(JudgeID);
            Console.WriteLine(scoreList);
            return scoreList;
        }

        // POST: CompetitionScore/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CompetitionScore Cscore)
        {
            if (ModelState.IsValid)
            {
                //Add score record to database
                Cscore.CompetitorID = scoreContext.Add(Cscore);
                //Redirect user to CompetitionScore/Index view
                return RedirectToAction("Index");
            }
            else
            {
                //Input validation fails, return to the Create view
                //to display error message
                return View(Cscore);
            }
        }

        // GET: CompetitionScore/Edit/5
        public ActionResult Edit(int? id)
        {
            // Stop accessing the action if not logged in
            // or account not in the "Judge" role           
            if ((HttpContext.Session.GetString("Role") == null) ||
            (HttpContext.Session.GetString("Role") != "Judge"))
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null)
            {
                //Query string parameter not provided
                //Return to listing page, not allowed to edit
                return RedirectToAction("Index");
            }

            CompetitionScore cscore = scoreContext.GetDetails(id.Value);

            if (cscore == null)
            {
                //Return to listing page, not allowed to edit
                return RedirectToAction("Index");
            }
            return View(cscore);
        }

        // POST: CompetitionScore/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CompetitionScore cscore)
        {
           // ViewData["CompetitionList"] = GetAllCompetition();
            if (ModelState.IsValid)
            {
                //Update submission score record to database
                scoreContext.Update(cscore);
                return RedirectToAction("Index");
            }
            else
            {
                //Input validation fails, return to the view
                //to display error message
                return View(cscore);
            }
        }
    }
}

WEB2021Apr_P04_T4/Views/CompetitionScore/Create.cshtml
@model WEB2021Apr_P04_T4.Models.CompetitionScore

@{
    ViewData["Title"] = "Create";
}

<h4 class="PageTitle">Add Competition Submission to grade</h4>
<hr />
<form asp-action="Create">
    <fieldset class="FormContent">
        <div class="form-group row">
            <label asp-for="CompetitionID"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                 <!-- Drop-down list displaying CompetitionName,
                with CompetitionID as returned value -->
                <select asp-for="CompetitionID"
                        asp-items="@(new SelectList(
 @ViewData["CompetitionList"] as List <Competition>,
 "CompetitionID", "CompetitionName"))"
                        class="form-control"></select>
                <span asp-validation-for="CompetitionID"
                      class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="CompetitorID"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="CompetitorID" class="form-control" />
                <span asp-validation-for="CompetitorID"
                      class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="CriteriaID"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <!-- Drop-down list displaying CompetitionName,
    with CompetitionID as returned value -->
                <select asp-for="CriteriaID"
                        asp-items="@(new SelectList(
 @ViewData["CriteriaList"] as List <Criteria>,
 "CriteriaID", "CriteriaName"))"
                        class="form-control"></select>
                <span asp-validation-for="CriteriaID"
                      class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Score"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="Score" class="form-control" />
                <span asp-validation-for="Score"
                      class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <input type="submit" value="Create"
                       class="btn btn-primary" />
            </div>
        </div>
        <div>
            <a asp-action="Index">Back to Scoresheet</a>
        </div>
    </fieldset>
</form>

WEB2021Apr_P04_T4/Views/CompetitionScore/Edit.cshtml
@model WEB2021Apr_P04_T4.Models.CompetitionScore

@{
    ViewData["Title"] = "Edit";
}

<h4 class="PageTitle">Edit Score</h4>
<hr />
<form asp-action="Edit">
    <fieldset class="FormContent">
        <div class="form-group row">
        </div>
        <div class="form-group row">
            <label asp-for="CompetitionID"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="CompetitionID" readonly
                       class="form-control-plaintext" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="CompetitorID"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="CompetitorID" readonly
                       class="form-control-plaintext" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="CriteriaID"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="CriteriaID" readonly
                       class="form-control-plaintext" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Score"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="Score" class="form-control" />
                <span asp-validation-for="Score"
                      class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <input type="submit" value="Save"
                       class="btn btn-primary" />
            </div>
        </div>
        <div>
            <a asp-action="Index">Back to List</a>
        </div>
    </fieldset>
</form>

WEB2021Apr_P04_T4/Views/CompetitionScore/Index.cshtml
@model IEnumerable<WEB2021Apr_P04_T4.Models.CompetitionScore>

@{
    ViewData["Title"] = "Index";
}

<h4 class="PageTitle">Competition Scores</h4>
<p><a asp-action="Create">Add Competition Submission to grade</a></p>
<!-- Add a partial view to display a list of competition score records
 in a tabular format. -->
<partial name="~/Views/CompetitionScore/_ViewCompetitionScore.cshtml" model="@Model" />

WEB2021Apr_P04_T4/Views/CompetitionScore/_ViewCompetitionScore.cshtml
@model IEnumerable<WEB2021Apr_P04_T4.Models.CompetitionScore>

@if (Model.ToList().Count > 0)
{
    <div class="table-responsive">
        <table id="viewCompetitionScore" class="table table-striped table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>Criteria ID</th>
                    <th>Competitor ID</th>
                    <th>Competition ID</th>
                    <th>Score</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td>@item.CriteriaID.ToString()</td>
                    <td>@item.CompetitorID.ToString()</td>
                    <td>@item.CompetitionID.ToString()</td>
                    <td>@item.Score.ToString()</td>
                    <td>
                        <a asp-action="Edit" asp-controller="CompetitionScore"
                           asp-route-id="@item.CompetitionID">Edit Score</a> |
                        <a asp-action="Details" asp-controller="CompetitionSubmission"
                           asp-route-id="@item.CompetitionID">Details</a>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <span style="color:red">No competition submission to grade.</span>
}