WEB2021Apr_P04_T4/Models/AreaInterest.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace WEB2021Apr_P04_T4.Models
{
    public class AreaInterest
    {
        [Display(Name = "ID")]
        [ValidateInterestDeletion]
        public int AreaInterestID { get; set; }

        [Required]
        [StringLength(50)]
        [ValidateInterestExists]
        public string Name { get; set; }

    }
}

WEB2021Apr_P04_T4/Controllers/AreaInterestController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WEB2021Apr_P04_T4.DAL;
using WEB2021Apr_P04_T4.Models;

namespace WEB2021Apr_P04_T4.Controllers
{
    public class AreaInterestController : Controller
    {
        private AreaInterestDAL areaInterestContext = new AreaInterestDAL();
        // GET: AreaInterestController
        public ActionResult Index()
        {
            // Stop accessing the action if not logged in or account not in the "Admin" role
            if ((HttpContext.Session.GetString("Role") == null) || (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }//Retrieve all available areaInterest from DB
            List<AreaInterest> areaInterestList = areaInterestContext.GetAllAreaInterest();
            //Pass all available areaInterest to Views
            return View(areaInterestList);
        }

        // GET: AreaInterestController/Create
        public ActionResult Create()
        {
            // Stop accessing the action if not logged in or account not in the "Admin" role
            if ((HttpContext.Session.GetString("Role") == null) || (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        // POST: AreaInterestController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AreaInterest areaInterest)
        {
            if (ModelState.IsValid)
            {
                //Add areaInterest record to database
                areaInterest.AreaInterestID = areaInterestContext.Add(areaInterest);
                //Redirect user to AreaInterest/Index view
                return RedirectToAction("Index");
            }
            else
            {
                //Input validation fails, return to the Create view to display error message
                return View(areaInterest);
            }
        }

        // GET: AreaInterestController/Delete/5
        public ActionResult Delete(int? id)
        {
            // Stop accessing the action if not logged in or account not in the "Admin" role
            if ((HttpContext.Session.GetString("Role") == null) || (HttpContext.Session.GetString("Role") != "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            // Stop accessing the action if requesting id is not valid
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            AreaInterest areaInterest = areaInterestContext.GetDetails(id.Value);
            //If interest has competition record, redirect to error and prevent deletion
            if (areaInterestContext.IsDeletable(id.Value))
            {
                TempData["ErrorMsg"] = "Sorry! A competition record has been made!";
                return RedirectToAction("DisplayError", "Home");
            }
            // Stop accessing the action if requesting id is not in database
            if (areaInterest.Name == null)
            {
                return RedirectToAction("Index");
            }
            return View(areaInterest);
        }

        // POST: AreaInterestController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(AreaInterest areaInterest)
        {
            if (ModelState.IsValid)
            {
                // Delete the interest record from database
                areaInterestContext.Delete(areaInterest.AreaInterestID);
                //Redirect user to AreaInterest/Index view
                return RedirectToAction("Index");
            }
            else
            {
                //Input validation fails, return to the Delete view to display error message
                return View(areaInterest);
            }
            
        }
    }
}

WEB2021Apr_P04_T4/Views/AreaInterest/Create.cshtml
@model WEB2021Apr_P04_T4.Models.AreaInterest

@{
    ViewData["Title"] = "Create Interest";
}

<h4 class="PageTitle">Create Interest</h4>
<hr />
<form asp-action="Create">
    <fieldset class="FormContent">
        <div class="form-group row">
            <label asp-for="Name"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name"
                      class="text-danger"></span>
            </div>
        </div>
        
        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <input type="submit" value="Create"
                       class="btn btn-primary" />
            </div>
        </div>
        <div>
            <a asp-action="Index">Return</a>
        </div>
    </fieldset>
</form>

WEB2021Apr_P04_T4/Views/AreaInterest/Delete.cshtml
@model WEB2021Apr_P04_T4.Models.AreaInterest

@{
    ViewData["Title"] = "Delete";
}

<h4 class="PageTitle">Delete Staff Record</h4>
<hr />
<form asp-action="Delete">
    <fieldset class="FormContent">
        <legend>Are you sure to delete this record?</legend>
        <div class="form-group row">
            <label asp-for="AreaInterestID"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="AreaInterestID" readonly
                       class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Name"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="Name" readonly
                       class="form-control-plaintext" />
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <span asp-validation-for="AreaInterestID"
                      class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <input type="submit" value="Delete"
                       class="btn btn-primary" />
            </div>
        </div>
        <div>
            <a asp-action="Index">Return</a>
        </div>
    </fieldset>
</form>

WEB2021Apr_P04_T4/Views/AreaInterest/Index.cshtml
@model IEnumerable<WEB2021Apr_P04_T4.Models.AreaInterest>

@{
    ViewData["Title"] = "View Interest";
}

<h4 class="PageTitle">View Interest</h4>
<p><a asp-action="Create">Create New Interest</a></p>
<!-- Add a partial view to display a list of records
 in a tabular format. -->
<partial name="~/Views/AreaInterest/_ViewAreaInterest.cshtml" model="@Model" />

WEB2021Apr_P04_T4/Views/AreaInterest/_ViewAreaInterest.cshtml
@model IEnumerable<WEB2021Apr_P04_T4.Models.AreaInterest>

@if (Model.ToList().Count > 0)
{
    <div class="table-responsive">
        <table id="viewStaff" class="table table-striped table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.AreaInterestID.ToString()</td>
                        <td>@item.Name </td>
                        <td>
                            <a asp-action="Delete" asp-controller="AreaInterest"
                               asp-route-id="@item.AreaInterestID">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <span style="color:red">No record found!</span>
}