WEB2021Apr_P04_T4/Controllers/JudgeProfileController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WEB2021Apr_P04_T4.DAL;
using WEB2021Apr_P04_T4.Models;

namespace WEB2021Apr_P04_T4.Controllers
{
    public class JudgeProfileController : Controller
    {
        private JudgeProfileDAL judgeContext = new JudgeProfileDAL();
        private AreaInterestDAL areaInterestContext = new AreaInterestDAL();
        public ActionResult Index()
        {
            string loginID = HttpContext.Session.GetString("LoginID");
            if ((HttpContext.Session.GetString("Role") == null) ||
            (HttpContext.Session.GetString("Role") != "Judge"))
            {
                return RedirectToAction("Index", "Home");
            }
            Judge judge = judgeContext.GetDetails(Convert.ToInt32(loginID));
            JudgeViewModel judgeVM = MapToJudgeVM(judge);
            return View(judgeVM);
        }     

        public JudgeViewModel MapToJudgeVM(Judge judge)
        {
            string interestName = "";
            if (judge.JudgeID != null)
            {
                List<AreaInterest> interestList = areaInterestContext.GetAllAreaInterest();
                foreach (AreaInterest interest in interestList)
                {
                    if (interest.AreaInterestID == judge.AreaInterestID)
                    {
                        interestName = interest.Name;
                        //Exit the foreach loop once the name is found
                        break;
                    }
                }
            }
            JudgeViewModel judgeVM = new JudgeViewModel
            {
                JudgeID = judge.JudgeID,
                JudgeName = judge.JudgeName,
                Salutation = judge.Salutation,
                AreaInterestID = interestName,
                EmailAddr = judge.EmailAddr,
                Password = judge.Password,
            };
            return judgeVM;        
    }

        private List<AreaInterest> GetAllAreaInterests()
        {
            // Get a list of branches from database
            List<AreaInterest> areaInterestList = areaInterestContext.GetAllAreaInterest();
            Console.WriteLine(areaInterestList);
            // Adding a select prompt at the first row of the branch list
            areaInterestList.Insert(0, new AreaInterest
            {
                AreaInterestID = 0,
                Name = "--Select--"
            });
            Console.WriteLine(areaInterestList);
            return areaInterestList;
        }

        // GET: JudgeProfileController/Create
        public ActionResult Create()
        {
            ViewData["InterestList"] = GetAllAreaInterests();
            return View();
        }

        // POST: JudgeProfileController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Judge judge)
        {
            ViewData["InterestList"] = GetAllAreaInterests();
            if (ModelState.IsValid)
            {
                //Add judge record to database
                judge.JudgeID = judgeContext.Add(judge);
                //Redirect user to Judge/Index view
                return RedirectToAction("Index");
            }
            else
            {
                //Input validation fails, return to the Create view
                //to display error message
                return View(judge);
            }
        }


        // GET: JudgeProfileController/Edit/5
        public ActionResult Edit(int? id)
        {
            // Stop accessing the action if not logged in
            // or account not in the "Judge" role

            if ((HttpContext.Session.GetString("LoginID") != id.ToString()) ||
            (HttpContext.Session.GetString("Role") != "Judge"))
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null)
            { //Query string parameter not provided
              //Return to listing page, not allowed to edit
                return RedirectToAction("Index", "Home");
            }
            ViewData["InterestList"] = GetAllAreaInterests();
            Judge judge = judgeContext.GetDetails(id.Value);
            if (judge == null)
            {
                //Return to listing page, not allowed to edit
                return RedirectToAction("Index", "Home");
            }
            return View(judge);
        }

        // POST: JudgeProfileController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Judge judge)
        {
            ViewData["InterestList"] = GetAllAreaInterests();

            if (ModelState.IsValid) {
                //Update judge record to database
                judgeContext.Update(judge);
                return RedirectToAction("Index");
            }
            else
            {
                //Input validation fails, return to the view
                //to display error message
                return View(judge);
            }
        }

        /*
        // GET: JudgeProfileController/Delete/5
        public ActionResult Delete(int? id)
        {
            // Stop accessing the action if not logged in or account not in the "Admin" role
            if ((HttpContext.Session.GetString("Role") == null) ||
                (HttpContext.Session.GetString("Role") != "Judge"))
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null)
            {
                //Return to listing page, not allowed to edit
                return RedirectToAction("Index");
            }
            Judge judge = judgeContext.GetDetails(id.Value);
            if (judge == null)
            {
                //Return to listing page, not allowed to edit
                return RedirectToAction("Index");
            }
            return View(judge);
        }

        // POST: JudgeProfileController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Judge judge)
        {
            // Delete the interest record from database
            judgeContext.Delete(judge.JudgeID);
            return RedirectToAction("Index");
        } */
    }
}

WEB2021Apr_P04_T4/Views/JudgeProfile/Create.cshtml
@model WEB2021Apr_P04_T4.Models.Judge

@{
    ViewData["Title"] = "Create";
}

<h4 class="PageTitle">Register Judge Account</h4>
<hr />
<form asp-action="Create">
    <fieldset class="FormContent">
        <div class="form-group row">
            <label asp-for="JudgeName"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="JudgeName" class="form-control" />
                <span asp-validation-for="JudgeName"
                      class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Salutation"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <div class="form-group form-check-inline">
                    <label class="col-form-label">
                        <input asp-for="Salutation" type="radio" value="Dr"
                               checked class="form-check-input" />
                        <span style="font-weight:normal;
 padding-right:20px">Dr</span>
                    </label>
                    <label class="col-form-label">
                        <input asp-for="Salutation" type="radio" value="Mr"
                               class="form-check-input" />
                        <span style="font-weight:normal;
 padding-right:20px">Mr</span>
                    </label>
                    <label class="col-form-label">
                        <input asp-for="Salutation" type="radio" value="Ms"
                               class="form-check-input" />
                        <span style="font-weight:normal;
 padding-right:20px">Ms</span>
                    </label>
                    <label class="col-form-label">
                        <input asp-for="Salutation" type="radio" value="Mrs"
                               class="form-check-input" />
                        <span style="font-weight:normal;
 padding-right:20px">Mrs</span>
                    </label>
                    <label class="col-form-label">
                        <input asp-for="Salutation" type="radio" value="Mdm"
                               class="form-check-input" />
                        <span style="font-weight:normal;
 padding-right:20px">Mdm</span>
                    </label>
                </div>
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="AreaInterestID"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <!-- Drop-down list displaying Branch Address,
        with Branch Number as returned value -->
                <select asp-for="AreaInterestID"
                        asp-items="@(new SelectList(
 @ViewData["InterestList"] as List <AreaInterest>,
 "AreaInterestID", "Name"))"
                        class="form-control"></select>
                <span asp-validation-for="AreaInterestID"
                      class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="EmailAddr"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="EmailAddr" class="form-control" />
                <span asp-validation-for="EmailAddr"
                      class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Password"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password"
                      class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <input type="submit" value="Register"
                       class="btn btn-primary" />
            </div>
        </div>
    </fieldset>
</form>

WEB2021Apr_P04_T4/Views/JudgeProfile/Delete.cshtml
@model WEB2021Apr_P04_T4.Models.Judge

@{
    ViewData["Title"] = "Delete";
}

<h4 class="PageTitle">Delete Judge Record</h4>
<hr />

<form asp-action="Delete">
    <fieldset class="FormContent">
        <legend>Are you sure to delete this record?</legend>
        <div class="form-group row">
            <label asp-for="JudgeID"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="JudgeID" readonly
                       class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="JudgeName"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="JudgeName" readonly
                       class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <input type="submit" value="Delete"
                       class="btn btn-primary" />
            </div>
        </div>
        <div>
            <a asp-action="Index">Back to List</a>
        </div>
    </fieldset>
</form>

WEB2021Apr_P04_T4/Views/JudgeProfile/Edit.cshtml
@model WEB2021Apr_P04_T4.Models.Judge

@{
    ViewData["Title"] = "Edit";
}

<h4 class="PageTitle">Edit Judge Record</h4>
<hr />
<form asp-action="Edit">
    <fieldset class="FormContent">
        <div class="form-group row">
            <label asp-for="JudgeID"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="JudgeID" readonly
                       class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="JudgeName"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="JudgeName" readonly
                       class="form-control-plaintext" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Salutation"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <div class="form-group form-check-inline">
                    <label class="col-form-label">
                        <input asp-for="Salutation" type="radio" value="Dr"
                               checked class="form-check-input" />
                        <span style="font-weight:normal;
 padding-right:20px">Dr</span>
                    </label>
                    <label class="col-form-label">
                        <input asp-for="Salutation" type="radio" value="Mr"
                               class="form-check-input" />
                        <span style="font-weight:normal;
 padding-right:20px">Mr</span>
                    </label>
                    <label class="col-form-label">
                        <input asp-for="Salutation" type="radio" value="Ms"
                               class="form-check-input" />
                        <span style="font-weight:normal;
 padding-right:20px">Ms</span>
                    </label>
                    <label class="col-form-label">
                        <input asp-for="Salutation" type="radio" value="Mrs"
                               class="form-check-input" />
                        <span style="font-weight:normal;
 padding-right:20px">Mrs</span>
                    </label>
                    <label class="col-form-label">
                        <input asp-for="Salutation" type="radio" value="Mdm"
                               class="form-check-input" />
                        <span style="font-weight:normal;
 padding-right:20px">Mdm</span>
                    </label>
                </div>
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="AreaInterestID"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <!-- Drop-down list displaying Branch Address,
            with Branch Number as returned value -->
                <select asp-for="AreaInterestID"
                        asp-items="@(new SelectList(
 @ViewData["InterestList"] as List <AreaInterest>,
 "AreaInterestID", "Name"))"
                        class="form-control"></select>
                <span asp-validation-for="AreaInterestID"
                      class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="EmailAddr"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="EmailAddr" class="form-control" />
                <span asp-validation-for="EmailAddr"
                      class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Password"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password"
                      class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <input type="submit" value="Save"
                       class="btn btn-primary" />
            </div>
        </div>
        <div>
            <a asp-action="Index">Back</a>
        </div>
    </fieldset>
</form>

WEB2021Apr_P04_T4/Views/JudgeProfile/Index.cshtml
@model WEB2021Apr_P04_T4.Models.JudgeViewModel

@{ ViewData["Title"] = "Details"; }

<h4 class="PageTitle">View Judge Details</h4>
<hr />
<fieldset class="FormContent">
    <div class="form-group row">
        <label asp-for="JudgeID"
               class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9 form-control-plaintext">
            @Html.Display("JudgeID")
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="JudgeName" class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9 form-control-plaintext">
            @Html.Display("JudgeName")
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Salutation" class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9 form-control-plaintext">
            @Html.Display("Salutation")
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Salutation" class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9">
            <div class="form-group form-check-inline">
                <label class="col-form-label">
                    <input asp-for="Salutation" type="radio" value="Dr"
                           class="form-check-input" disabled />
                    <span style="font-weight:normal;
 padding-right:20px">Dr</span>
                </label>
                <label class="col-form-label">
                    <input asp-for="Salutation" type="radio" value="Mr"
                           class="form-check-input" disabled />
                    <span style="font-weight:normal;
 padding-right:20px">Mr</span>
                </label>
                <label class="col-form-label">
                    <input asp-for="Salutation" type="radio" value="Ms"
                           class="form-check-input" disabled />
                    <span style="font-weight:normal;
 padding-right:20px">Ms</span>
                </label>
                <label class="col-form-label">
                    <input asp-for="Salutation" type="radio" value="Mrs"
                           class="form-check-input" disabled />
                    <span style="font-weight:normal;
 padding-right:20px">Mrs</span>
                </label>
                <label class="col-form-label">
                    <input asp-for="Salutation" type="radio" value="Mdm"
                           class="form-check-input" disabled />
                    <span style="font-weight:normal;
 padding-right:20px">Mdm</span>
                </label>
            </div>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="AreaInterestID" class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9 form-control-plaintext">
            @Html.Display("AreaInterestID")
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="EmailAddr"
               class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9 form-control-plaintext">
            @Html.Display("EmailAddr")
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Password" class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9 form-control-plaintext">
            @Html.Display("Password")
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-9 offset-sm-3">
            <a asp-action="Edit" asp-controller="JudgeProfile"
               asp-route-id="@Context.Session.GetString("LoginID")">Edit</a> 
        </div>
    </div>
</fieldset>

WEB2021Apr_P04_T4/Views/JudgeProfile/_ViewJudgeProfile.cshtml
@model WEB2021Apr_P04_T4.Models.JudgeViewModel



@{ ViewData["Title"] = "Details"; }



<h4 class="PageTitle">View Judge Details</h4>
<hr />
<fieldset class="FormContent">
    <div class="form-group row">
        <label asp-for="JudgeID"
               class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9 form-control-plaintext">
            @Html.Display("JudgeID")
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="JudgeName" class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9 form-control-plaintext">
            @Html.Display("JudgeName")
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Salutation" class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9 form-control-plaintext">
            @Html.Display("Salutation")
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Salutation" class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9">
            <div class="form-group form-check-inline">
                <label class="col-form-label">
                    <input asp-for="Salutation" type="radio" value="Dr"
                           class="form-check-input" disabled />
                    <span style="font-weight:normal;
 padding-right:20px">Dr</span>
                </label>
                <label class="col-form-label">
                    <input asp-for="Salutation" type="radio" value="Mr"
                           class="form-check-input" disabled />
                    <span style="font-weight:normal;
 padding-right:20px">Mr</span>
                </label>
                <label class="col-form-label">
                    <input asp-for="Salutation" type="radio" value="Ms"
                           class="form-check-input" disabled />
                    <span style="font-weight:normal;
 padding-right:20px">Ms</span>
                </label>
                <label class="col-form-label">
                    <input asp-for="Salutation" type="radio" value="Mrs"
                           class="form-check-input" disabled />
                    <span style="font-weight:normal;
 padding-right:20px">Mrs</span>
                </label>
                <label class="col-form-label">
                    <input asp-for="Salutation" type="radio" value="Mdm"
                           class="form-check-input" disabled />
                    <span style="font-weight:normal;
 padding-right:20px">Mdm</span>
                </label>
            </div>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="AreaInterestID" class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9 form-control-plaintext">
            @Html.Display("AreaInterestID")
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="EmailAddr"
               class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9 form-control-plaintext">
            @Html.Display("EmailAddr")
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Password" class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9 form-control-plaintext">
            @Html.Display("Password")
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-9 offset-sm-3">
            <a asp-action="Edit" asp-controller="JudgeProfile"
               asp-route-id="@Context.Session.GetString("LoginID")">Edit</a> |
            <a asp-action="Index"
               asp-controller="JudgeProfile">Back to Judge List</a>
        </div>
    </div>
</fieldset>